### ISSUE TITLE
Can I...

### ISSUE THREAD

**Issue by tellio** [Rhizome-Conifer/conifer-user-guide#2]
Wanting to embed my warc files on a WordPress blog.  Possible?

**Comment by m4rk3r** [comment]
Hi @tellio, we support adding interactive embeds of items from webrecorder via the share widget:
![screen shot 2019-01-09 at 4 44 09 pm](https://user-images.githubusercontent.com/216952/50931008-788c7480-142f-11e9-87dc-0a255a94887d.png)

The embed code within the share widget box contains an iframe pointing to the page that is currently being played back. 

Here's an example utilizing webrecorder embeds: 
https://rhizome.org/editorial/2015/aug/6/why-museum-collect-vines/

If you're just trying to share the WARC file itself, the best way to go about that would be to download it and then host it elsewhere and link to it.
