### ISSUE TITLE
Exclude any 'live web' when extracting from WayBackMachine (and other web archives(?)) links ?

### ISSUE THREAD

**Issue by ghost** [Rhizome-Conifer/conifer-user-guide#3]
When using links from WayBackMachine to extract a no longer existing webpage, for some reason the extraction also seem to attempt to patch from 'live web', instead of just using Internet Archive as source; 

This seems to sometimes cause the extraction session to end up as a simple live-version of e.g **"This page no longer exist"** , even if there's extensive data on the supplied WayBackMachine link used for extraction.

_(I guess this is caused by some websites not responding with proper http response, even though the page no longer exist/is available from/on their end..)_

Any way to circumvent that, and patch exclusively from what's available at e.g WayBackMachine ?

**Comment by m4rk3r** [comment]
In the extraction widget, you can deselect the "live web" checkbox to limit extraction to the targeted archive. 

![image](https://user-images.githubusercontent.com/216952/97454187-dba11100-190c-11eb-8a45-291aac4eb386.png)
