### ISSUE TITLE
stalls after indexing

### ISSUE THREAD

**Issue by Ajxfn** [Rhizome-Conifer/conifer-user-guide#4]
Hi
i have downloaded multiple warc files of a single webdomain/site. These files are about 5,2gb big (x11). But I can't open a single file in the WebrecorderPlayer. The Player always loads to 100% (Please wait while the archive is indeced). That takes about 2 Minutes then it stops and gives a an error message:

Oops,_ it seems that indexing has stalled. Additional info ...

Created user local with the email test@localhost and the role: 'public-archivist' 
WARCSERVER_HOST=http://localhost:55584 

APP_HOST=http://localhost:55585

**Comment by m4rk3r** [comment]
Hi @Ajxfn, the Webrecorder Player is now being maintained by Webrecorder.net org, see more info here: https://github.com/webrecorder/webrecorder-player
