### ISSUE TITLE
Unable to "disable protection" on Desktop app

### ISSUE THREAD

**Issue by webctrl** [Rhizome-Conifer/conifer-user-guide#5]
Hi,

Some content is blocked on the desktop app, and also on the Chrome browsers on the site. On webrecorder.io if you select one of the Firefox browsers there's an in-browser option to "Disable protection for now". For example on this page: https://www.bbc.co.uk/blogs/markkermode/2009/01/more_points_of_you_part_two.html there's a video that I cannot see at all in the Desktop app, however on webrecorder.io using Firefox v68 I can "Disable protection for now" and then play the video. 

Are there any plans to add a Firefox option to the Desktop app, or find another way around this issue?

Thank you.

**Comment by m4rk3r** [comment]
Hi @webctrl, the Webrecorder Desktop app is now maintained by our collaborators at the Webrecorder.net org, you can open an issue with them here: https://github.com/webrecorder/webrecorder-desktop
